DataViz/urls.py
"""
Definition of urls for DataViz.
"""

# urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

admin.autodiscover()

favicon_view = RedirectView.as_view(url='/static/app/favicon.png', permanent=True)

urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^admin/', admin.site.urls)
]

# Active DEBUG Toolbar
# if settings.DEBUG:
#    import debug_toolbar

#    urlpatterns = [
#                      url(r'^__debug__', include(debug_toolbar.urls))
#                  ] + urlpatterns

# This is only required to support extension-style formats (e.g. /data.csv)


static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.conf.urls import url
from app import views

# Template urls
app_name = "app"

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^home', views.home, name='home'),
    url(r'^clusters', views.clusters, name='clusters'),
    url(r'^page_cluster', views.page_cluster, name='page_cluster'),
    url(r'^filters', views.filters, name='filters'),
    # url(r'^list_catalogs', views.list_catalogs, name='list_catalogs'),
    url(r'^schedule_process', views.schedule_process, name='schedule_process'),
    url(r'^process_catalog_finished', views.process_catalog_finished, name='process_catalog_finished'),
    url(r'^publish_catalog', views.publish_catalog, name='publish_catalog'),
    url(r'^set_catalog', views.set_catalog, name='set_catalog'),
    url(r'^get_catalog_info', views.get_catalog_info, name='get_catalog_info'),
    url(r'^get_statistics_info', views.get_statistics_info, name='get_statistics_info'),
    url(r'^testebq', views.testebq, name='testebq'),
    url(r'^set_row_main', views.set_row_main, name='set_row_main'),
    url(r'^set_wrong', views.set_wrong, name='set_wrong'),
    url(r'^set_comment', views.set_comment, name='set_comment'),
    url(r'^get_comment', views.get_comment, name='get_comment'),
    url(r'^report_n1_headers', views.report_n1_headers, name='report_n1_headers'),
    url(r'^report_n2_headers', views.report_n2_headers, name='report_n2_headers'),
    url(r'^report_n1_items', views.report_n1_items, name='report_n1_items'),
    url(r'^report_n2_items', views.report_n2_items, name='report_n2_items'),
    url(r'^settings', views.settings, name='settings'),
    url(r'^report', views.report, name='report'),
    url(r'^graph', views.graph, name='graph'),
    url(r'^graph_render', views.graph_render, name='graph_render'),
    url(r'^set_filter', views.set_filter, name='set_filter'),
    url(r'^clear_filters', views.clear_filters, name='clear_filters'),
    url(r'^quantity_per_page', views.quantity_per_page, name='quantity_per_page'),
    url(r'^set_quantity_per_page', views.set_quantity_per_page, name='set_quantity_per_page'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

templates/app/clusters.1.html
{% extends "app/layout.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <a name="top-page"/>
        <v-container
                fluid
                style="min-height: 0;"
                grid-list-xs>

            <v-card flat class="py-0" color="grey lighten-3">
                <v-toolbar dense card height="40px">
                    <v-toolbar-title class="body-2 font-weight 500">Catalog Version 1.0</v-toolbar-title>
                    <v-spacer></v-spacer>
                    <v-toolbar-items class="hidden-sm-and-down">
                        <div style="margin-top: 10px;">Qty/Page</div>
                        <div style="margin-top: 5px; margin-left: 5px;">
                            <v-flex>
                                <v-select
                                        :items="itemsquantitypage"
                                        item-text="item"
                                        item-value="value"
                                        v-model="modelquantitypage"
                                        single-line
                                        persistent-hint
                                        id="comboquantityperpage"
                                >
                                </v-select>
                            </v-flex>
                        </div>
                        <v-btn flat value="center" @click.stop="rightDrawer = !rightDrawer">
                            <v-icon>filter_list</v-icon>
                            <span>[[filterButtonLabel]]</span>
                        </v-btn>
                        <v-spacer></v-spacer>
                    </v-toolbar-items>
                </v-toolbar>
            </v-card>
        </v-container>
        <v-container fluid fill-height>
            <v-layout
                    justify-center
                    align-center>
                <v-layout row>
                    <v-flex>
                        <template v-for="cluster in items">
                            <v-container
                                    fluid
                                    style="min-height: 0;"
                                    grid-list-sm>
                                <v-card>
                                    <v-toolbar dense flat card height="40px">
                                        <v-toolbar-title class="body-2 font-weight 500">[[cluster.cluster_id + ' - # Items: ' + cluster.cluster_items.length]]
                                        </v-toolbar-title>
                                    </v-toolbar>
                                    <v-data-table
                                            :headers="headers"
                                            :items="cluster.cluster_items"
                                            hide-actions
                                            class="elevation-1"
                                            :loading="loading"
											dense

                                    >
                                        <template slot="items" slot-scope="props">
											<template v-for="head in headers">
												<td v-if="head.type == 'user'" :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 1)" v-html="props.item[head.value]"></td>
												<td v-if="head.type == 'img'" :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 1)"><img v-bind:src="props.item[head.value]" alt="" height="65px" width="65px"/></td>
											</template>
                                            <!--<a v-bind:href="props.item[head.value]"> "props.item[head.value]"<img v-bind:src="props.item[head.value]" width="65" height="65" /></a>-->
                                            <td :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 2)"v-html="props.item.count" ></td>
                                            <td :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 2)">
                                                {% comment %}rowMainArray.indexOf(props.item.index) > -1{% endcomment %}
                                                <v-icon color="amber lighten-1" :ref="props.item.index" v-if="props.item.ROW_MAIN == 1" @click="starClick(cluster.cluster_id, props.item.ROW_INDEX)">star</v-icon>
                                                <v-icon color="amber lighten-1" :ref="props.item.index" v-else @click="starClick(cluster.cluster_id, props.item.ROW_INDEX)">star_border</v-icon>
                                                <v-icon color="red lighten-1" v-if="props.item.WRONG == '1'" @click="wrongClick(cluster.cluster_id, props.item.ROW_INDEX)">cancel</v-icon>
                                                <v-icon color="red lighten-1" v-else @click="wrongClick(cluster.cluster_id, props.item.ROW_INDEX)">close</v-icon>
                                                <v-icon color="primary" v-if="props.item.COMMENT != ''" @click="commentClick(cluster.cluster_id, props.item.ROW_INDEX)">chat_bubble</v-icon>
                                                <v-icon color="primary" v-else @click="commentClick(cluster.cluster_id, props.item.ROW_INDEX)">chat_bubble_outline</v-icon>
                                            </td>
                                        </template>
                                    </v-data-table>
                                </v-card>
                            </v-container>
                            <v-divider></v-divider>
                        </template>
                        <v-dialog v-model="dialogComment" max-width="550px">
                            <v-card>
                                <v-card-text>
                                    <template>
                                        <v-text-field
                                                label="Comment"
                                                multi-line
                                                v-model="inputCommentModel"
                                        ></v-text-field>
                                    </template>
                                </v-card-text>
                                <v-card-actions>
                                    <v-spacer></v-spacer>
                                    <v-btn color="primary" flat @click.stop="dialogComment=false">Cancel</v-btn>
                                    <v-btn color="green" flat @click.stop="updateComment();">Save</v-btn>
                                </v-card-actions>
                            </v-card>
                        </v-dialog>

                        <v-progress-linear v-show="loading" indeterminate></v-progress-linear>

                        <div class="text-xs-center">
                            <v-pagination :length="pages" v-model="page" :total-visible="10"
                                          @click.native="scrollToAnchor"></v-pagination>
                        </div>
                    </v-flex>
                </v-layout>
            </v-layout>
        </v-container>
    {% else %}
        <div style="text-align: center; margin-top: 100px;">
            <v-btn color="primary" style="text-align: center" href="{% url 'app:user_login' %}">Log In</v-btn>
        </div>
    {% endif %}
{% endblock %}
{% block tail %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            getCatalogStatus();
        });
    </script>
{% endblock %}

templates/app/clusters.html
{% extends "app/layout.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <a name="top-page"/>
        <v-container
                fluid
                style="min-height: 0;"
                grid-list-xs>

            <v-card flat class="py-0" color="grey lighten-3">
                <v-toolbar dense card height="40px">
                    <v-toolbar-title class="body-2 font-weight 500">Catalog Version 1.0</v-toolbar-title>
                    <v-spacer></v-spacer>
                    <v-toolbar-items class="hidden-sm-and-down">
                        <div style="margin-top: 10px;">Qty/Page</div>
                        <div style="margin-top: 5px; margin-left: 5px;">
                            <v-flex>
                                <v-select
                                        :items="itemsquantitypage"
                                        item-text="item"
                                        item-value="value"
                                        v-model="modelquantitypage"
                                        single-line
                                        persistent-hint
                                        id="comboquantityperpage"
                                >
                                </v-select>
                            </v-flex>
                        </div>
                        <v-btn flat value="center" @click.stop="rightDrawer = !rightDrawer">
                            <v-icon>filter_list</v-icon>
                            <span>[[filterButtonLabel]]</span>
                        </v-btn>
                        <v-spacer></v-spacer>
                    </v-toolbar-items>
                </v-toolbar>
            </v-card>
        </v-container>
        <v-container fluid fill-height>
            <v-layout
                    justify-center
                    align-center>
                <v-layout row>
                    <v-flex>
                        <template v-for="cluster in items">
                            <v-container
                                    fluid
                                    style="min-height: 0;"
                                    grid-list-sm>
                                <v-card>
                                    <v-toolbar dense flat card height="40px">
                                        <v-toolbar-title class="body-2 font-weight 500">[[cluster.cluster_id + ' - # Items: ' + cluster.cluster_items.length]]
                                        </v-toolbar-title>
                                    </v-toolbar>
                                    <v-data-table
                                            :headers="headers"
                                            :items="cluster.cluster_items"
                                            hide-actions
                                            class="elevation-1"
                                            :loading="loading"
											dense

                                    >

                                        <template slot="items" slot-scope="props">
                                        <!--<tr class="sortableRow" :key="itemKey(props.item.ROW_INDEX)">-->
                                            <!-- <td class="px-1" style="width: 0.1%">
                                                <v-btn style="cursor: move" icon class="sortHandle"><v-icon>drag_handle</v-icon></v-btn>
                                            </td> -->
                                            <template v-for="head in headers">
												<td v-if="head.type == 'user'" :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 1)" v-html="props.item[head.value]"></td>
												<td v-if="head.type == 'img'" :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 1)"><img v-bind:src="props.item[head.value]" alt="" height="65px" width="65px"/></td>
											</template>
                                            <td :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 2)"v-html="props.item.count" ></td>
                                            <td :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 2)"v-html="props.item.ROW_INDEX" ></td>
                                            <td :class="classChanger(props.item.ROW_MAIN, props.item.WRONG, 2)">
                                                {% comment %}rowMainArray.indexOf(props.item.index) > -1{% endcomment %}
                                                <v-icon color="amber lighten-1" :ref="props.item.index" v-if="props.item.ROW_MAIN == 1" @click="starClick(cluster.cluster_id, props.item.ROW_INDEX)">star</v-icon>
                                                <v-icon color="amber lighten-1" :ref="props.item.index" v-else @click="starClick(cluster.cluster_id, props.item.ROW_INDEX)">star_border</v-icon>
                                                <v-icon color="red lighten-1" v-if="props.item.WRONG == '1'" @click="wrongClick(cluster.cluster_id, props.item.ROW_INDEX)">cancel</v-icon>
                                                <v-icon color="red lighten-1" v-else @click="wrongClick(cluster.cluster_id, props.item.ROW_INDEX)">close</v-icon>
                                                <v-icon color="primary" v-if="props.item.COMMENT != ''" @click="commentClick(cluster.cluster_id, props.item.ROW_INDEX)">chat_bubble</v-icon>
                                                <v-icon color="primary" v-else @click="commentClick(cluster.cluster_id, props.item.ROW_INDEX)">chat_bubble_outline</v-icon>
                                            </td>
                                       <!-- </tr>-->
                                        </template>
                                    </v-data-table>
                                </v-card>
                            </v-container>
                            <v-divider></v-divider>
                        </template>
                        <v-dialog v-model="dialogComment" max-width="550px">
                            <v-card>
                                <v-card-text>
                                    <template>
                                        <v-text-field
                                                label="Comment"
                                                multi-line
                                                v-model="inputCommentModel"
                                        ></v-text-field>
                                    </template>
                                </v-card-text>
                                <v-card-actions>
                                    <v-spacer></v-spacer>
                                    <v-btn color="primary" flat @click.stop="dialogComment=false">Cancel</v-btn>
                                    <v-btn color="green" flat @click.stop="updateComment();">Save</v-btn>
                                </v-card-actions>
                            </v-card>
                        </v-dialog>

                        <v-progress-linear v-show="loading" indeterminate></v-progress-linear>

                        <div class="text-xs-center">
                            <v-pagination :length="pages" v-model="page" :total-visible="10"
                                          @click.native="scrollToAnchor"></v-pagination>
                        </div>
                    </v-flex>
                </v-layout>
            </v-layout>
        </v-container>
    {% else %}
        <div style="text-align: center; margin-top: 100px;">
            <v-btn color="primary" style="text-align: center" href="{% url 'app:user_login' %}">Log In</v-btn>
        </div>
    {% endif %}
{% endblock %}
{% block tail %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            getCatalogStatus();
        });
    </script>
{% endblock %}

templates/app/graph.html
{% extends "app/layout.html" %}
{% block content %}
    <template>
        <v-card
                flat
                class="pa-3"
        >
            <h2>3D Clusters Visualization</h2>
            <div id="graph-element" width="100%" height="100%"></div>
        </v-card>
    </template>
{% endblock %}
{% block tail %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            graph();
            getCatalogStatus();
        });
    </script>
{% endblock %}

templates/app/home.html
{% extends "app/layout.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <v-tabs fixed>
            <v-tabs-bar>
                <v-tabs-slider color="primary"></v-tabs-slider>
                <v-tabs-item href="tab-1">
                    DASHBOARD
                </v-tabs-item>
                <v-tabs-item href="tab-2">
                    ACTIVITY
                </v-tabs-item>
            </v-tabs-bar>
            <v-tabs-items>
                <v-tabs-content id="tab-1">
                    <v-card flat class="grey lighten-4">
                        <v-card-text>
                            <v-container fluid fill-height>
                                <v-layout column>
                                    <v-flex xs12 sm8 offset-sm2>
                                        <v-container fluid grid-list-md class="grey lighten-4">
                                            <v-layout row wrap>
                                                <v-flex xs6>
                                                    <v-card>
                                                        <v-card-media>
                                                            <v-container fill-height fluid>
                                                                <v-layout fill-height>
                                                                    <v-flex xs12 align-end flexbox>
                                                                        <span class="headline grey--text">Catalog Info</span>
                                                                    </v-flex>
                                                                </v-layout>
                                                            </v-container>
                                                        </v-card-media>
                                                        <v-card-title>
                                                            <div>
                                                                <span class="grey--text">Name:</span><br><span
                                                                    v-text="catalogInfo.catalogName"></span><br>
                                                                <span class="grey--text">Version:</span><br><span
                                                                    v-text="catalogInfo.catalogVersion"></span><br>
                                                                <span class="grey--text">Status:</span><br><span
                                                                    v-text="catalogInfo.catalogStatus"></span><br>
                                                                <span class="grey--text">Date:</span><br><span
                                                                    v-text="catalogInfo.catalogDate"></span><br>
                                                            </div>
                                                        </v-card-title>
                                                        <v-divider></v-divider>
                                                        <v-card-actions class="white">
                                                            <v-btn flat color="blue" :disabled="!canProcess"
                                                                   @click="processCatalog">Process
                                                            </v-btn>
                                                            <!--<v-btn flat color="green" :disabled="!canPublish"-->
                                                            <v-btn flat color="green"
                                                                   @click="publishCatalog">Publish
                                                            </v-btn>
                                                        </v-card-actions>
                                                    </v-card>
                                                </v-flex>
                                                <v-flex xs6>
                                                    <v-card>
                                                        <v-card-media>
                                                            <v-container fill-height fluid>
                                                                <v-layout fill-height>
                                                                    <v-flex xs12 align-end flexbox>
                                                                        <span class="headline grey--text">Statistics</span>
                                                                    </v-flex>
                                                                </v-layout>
                                                            </v-container>
                                                        </v-card-media>
                                                        <v-card-title>
                                                            <div>
                                                                <span class="grey--text"># Clusters:</span><br><span
                                                                    v-text="statisticsInfo.clusterNumber"></span><br>
                                                                <span class="grey--text"># Items:</span><br><span
                                                                    v-text="statisticsInfo.clusterItems"></span><br>
                                                                <span class="grey--text"># Items Interacted:</span><br><span
                                                                    v-text="statisticsInfo.clustersInteracted"></span><br>
                                                            </div>
                                                        </v-card-title>
                                                        <v-divider></v-divider>
                                                        <v-card-actions class="white">
                                                            <v-btn flat color="grey" href="{% url 'app:report' %}">GO TO
                                                                STATISTICS<span>&nbsp;</span>
                                                                <v-icon>forward</v-icon>
                                                            </v-btn>
                                                        </v-card-actions>
                                                    </v-card>
                                                </v-flex>
                                            </v-layout>
                                        </v-container>
                                    </v-flex>
                                </v-layout>
                            </v-container>
                        </v-card-text>
                    </v-card>
                </v-tabs-content>
            </v-tabs-items>
            <v-tabs-content id="tab-2">
                <v-card flat class="grey lighten-4">
                    <v-card-text>
                        NO ACTIVITIES TO SHOW
                    </v-card-text>
                </v-card>
            </v-tabs-content>
        </v-tabs>
    {% else %}
        <div style="text-align: center; margin-top: 100px;">
            <v-btn color="primary" style="text-align: center" href="{% url 'app:user_login' %}">Log In</v-btn>
        </div>
    {% endif %}
{% endblock %}
{% block tail %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            getCatalogStatus();
        });
    </script>
{% endblock %}

templates/app/login.html
{% extends "app/layout.html" %}
{% block content %}
    <template>
        <v-container fluid fill-height>
            <v-layout column>
                <v-flex xs12 sm12 offset-sm4>
                    <v-container fluid grid-list-md class="grey lighten-4">
                        <v-layout row wrap>
                            <v-flex xs6>
                                <v-card>
                                    <v-card-media>
                                        <v-container fluid>
                                            <v-layout>
                                                <v-flex xs12 align-end flexbox>
                                                    <span class="headline grey--text">Login</span>
                                                </v-flex>
                                            </v-layout>
                                        </v-container>
                                    </v-card-media>
                                    <v-card-text>
                                        <v-container fluid>
                                            <v-layout>
                                                <v-flex xs12 align-end flexbox>
                                                    <div class="text-md-center">
                                                        <v-form v-model="valid" ref="form">
                                                            <v-text-field
                                                                    v-model="userModel"
                                                                    label="User"
                                                                    required
                                                                    :rules="userRules"
                                                            ></v-text-field>
                                                            <v-text-field
                                                                    v-model="passwordModel"
                                                                    label="Enter your password"
                                                                    hint="At least 8 characters"
                                                                    required
                                                                    :rules="passwordRules"
                                                                    :append-icon="e3 ? 'visibility' : 'visibility_off'"
                                                                    :append-icon-cb="() => (e3 = !e3)"
                                                                    type="password"
                                                                    class="input-group--focused"
                                                                    :type="e3 ? 'password' : 'text'"
                                                            ></v-text-field>
                                                        </v-form>
                                                    </div>
                                                    <v-alert outline color="error" icon="warning" :value="errorLogin"
                                                             v-model="errorAlert" transition="scale-transition">
                                                        <div v-text="errorLogin"></div>
                                                    </v-alert>
                                                </v-flex>
                                            </v-layout>
                                        </v-container>
                                    </v-card-text>
                                    <v-card-actions class="white">
                                         <v-container fluid>
                                            <v-layout>
                                                <v-flex text-xs-right flexbox>
                                                    <v-spacer></v-spacer>
                                                    <v-btn @click="login">login</v-btn>
                                                    <v-btn href="{% url 'app:register' %}">register</v-btn>
                                                </v-flex>
                                            </v-layout>
                                         </v-container>
                                    </v-card-actions>
                                </v-card>
                            </v-flex>
                        </v-layout>
                    </v-container>
                </v-flex>
            </v-layout>
        </v-container>
    </template>
{% endblock %}

templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'user_login' %}">Log in</a></li>
</ul>

{% endif %}